### ISSUE TITLE
Add to readme

### ISSUE THREAD

**Issue by LaLeonie** [fac18/kgbj-week-6#34]
Your readme looks great so far, I particularly like the user journey. There's just a few things missing. Most importantly, please add installation guidelines to the start. Don't forget to add information on how to set up the local database, here is a snippet of our readme as an example:

<img width="1171" alt="Screenshot 2019-12-06 at 09 17 46" src="https://user-images.githubusercontent.com/45558475/70311339-61a1fe00-1809-11ea-8bc0-74a7afb9020d.png">

**Comment by LaLeonie** [comment]
It also would be great if you could explain the logic behind the sortingHat function i.e. explain what decides which house the user is allocated to

**Comment by bethanyios** [comment]
Thanks Leonie will do!
