### ISSUE TITLE
Where do you run db_build? 

### ISSUE THREAD

**Issue by LaLeonie** [fac18/kgbj-week-6#36]
You declared your db_build function in db_build.js, but it seems that you're not running this function anywhere apart from the db.test.js file.  Don't forget that this function needs to be run anytime someone installs your project i.e. creates a local database. So to test your app, I've created a db_init.js file which runs the function: 
```
const runBuild = require("./db_build");
runBuild((err, res) => {
  console.log("DATABASE CREATED", err, res);
});
```

And then I added a command to package.json to run this file: 
 `"db_init": "node src/database/db_init.js"`

I assume that you managed to run your app locally, so would be interesting to know how you initiated the database i.e. where you run the function...

**Comment by AlexandraOM** [comment]
Thanks Leonie! You're right, we did run into a few issues when we made changes to our db build file that it didn't restart itself with the new information or new columns. We solved this locally by going into the database and re-initialising it from there - but it took us a while to understand why it didn't do it automatically. Now it all makes sense!! 
Still need to work out how to make it work and how to update the database on heroku too...:/
