### ISSUE TITLE
Code clean up 

### ISSUE THREAD

**Issue by LaLeonie** [fac18/kgbj-week-6#39]
Your code looks pretty clean as it is but you can clean it up a bit more by: 
1.) Removing all the console.logs
2.) Removing the unused variables (I noticed some in your test files)

**Comment by LaLeonie** [comment]
I've also noticed that you mix ES5 and ES6 syntax to declare functions. In your public folder you use function declaration as opposed to arrow functions in your src folder. It's best to stick with one approach wherever you can for consistency.

**Comment by LaLeonie** [comment]
You're also using a lot of vars in your code. Better stick with let and const.

**Comment by LaLeonie** [comment]
Also, delete the houses.html page if you're not using it

**Comment by bethanyios** [comment]
Thanks Leonie :):):)
