### ISSUE TITLE
404 enhancement 

### ISSUE THREAD

**Issue by LaLeonie** [fac18/kgbj-week-6#42]
Great job for remembering and implementing the 404 page. It would be great if you could add a button or link for the user to go back to muggle school

**Comment by renatajarmova** [comment]
Agree! It looks great - well done you! 

But as Leonie said it would be great if you could add a button that redirects back to the home page.

**Comment by renatajarmova** [comment]
Oh, you could also center the text and maybe the button if you decide to add this!
