### ISSUE TITLE
Banging project

### ISSUE THREAD

**Issue by plasticneuron** [fac18/kgbj-week-6#58]
Hey gang, I actually struggled to find anything to pull you up on... Beautiful project! What can I say.

I really enjoyed the crucial sortingHat function in your handlers.js function. Two filters **inside** a reduce?! It's my lucky day.

Maybe you could move that into a logic file and test it as well? Since as far as I can tell it's pure?

![](https://media.giphy.com/media/QAsBwSjx9zVKoGp9nr/giphy.gif)

**Comment by bethanyios** [comment]
thanks Dan that is such a nice complimenttttt
